[2023-02-02 10:33:20,359] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster manual__2023-02-02T16:25:47.088667+00:00 [queued]>
[2023-02-02 10:33:20,382] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster manual__2023-02-02T16:25:47.088667+00:00 [queued]>
[2023-02-02 10:33:20,383] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-02 10:33:20,383] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-02-02 10:33:20,384] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-02 10:33:20,419] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster> on 2023-02-02 16:25:47.088667+00:00
[2023-02-02 10:33:20,421] {standard_task_runner.py:52} INFO - Started process 18234 to run task
[2023-02-02 10:33:20,423] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '6_dataproc_airflow', 'create_cluster', 'manual__2023-02-02T16:25:47.088667+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/Airflow2_0_De_0_a_Heroe/6_dataproc_airflow.py', '--cfg-path', '/tmp/tmpjncqrne_', '--error-file', '/tmp/tmppe1evllt']
[2023-02-02 10:33:20,425] {standard_task_runner.py:80} INFO - Job 174: Subtask create_cluster
[2023-02-02 10:33:20,514] {task_command.py:369} INFO - Running <TaskInstance: 6_dataproc_airflow.create_cluster manual__2023-02-02T16:25:47.088667+00:00 [running]> on host Tinmar.
[2023-02-02 10:33:20,639] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=David S
AIRFLOW_CTX_DAG_ID=6_dataproc_airflow
AIRFLOW_CTX_TASK_ID=create_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-02-02T16:25:47.088667+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-02T16:25:47.088667+00:00
[2023-02-02 10:33:20,640] {dataproc.py:591} INFO - Creating cluster: airflow-spark-cluster
[2023-02-02 10:33:20,653] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-02 10:36:04,975] {dataproc.py:535} INFO - Cluster created.
[2023-02-02 10:36:05,033] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=6_dataproc_airflow, task_id=create_cluster, execution_date=20230202T162547, start_date=20230202T163320, end_date=20230202T163605
[2023-02-02 10:36:05,090] {local_task_job.py:156} INFO - Task exited with return code 0
