[2023-02-13 14:59:57,119] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: branch_octavo_dag.api_call manual__2023-02-13T20:58:41.538479+00:00 [queued]>
[2023-02-13 14:59:57,124] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: branch_octavo_dag.api_call manual__2023-02-13T20:58:41.538479+00:00 [queued]>
[2023-02-13 14:59:57,125] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-13 14:59:57,125] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-02-13 14:59:57,126] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-13 14:59:57,134] {taskinstance.py:1377} INFO - Executing <Task(SimpleHttpOperator): api_call> on 2023-02-13 20:58:41.538479+00:00
[2023-02-13 14:59:57,137] {standard_task_runner.py:52} INFO - Started process 215888 to run task
[2023-02-13 14:59:57,139] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'branch_octavo_dag', 'api_call', 'manual__2023-02-13T20:58:41.538479+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/Apache_Airflow/branch_octavo_dag.py', '--cfg-path', '/tmp/tmp65yv44ta', '--error-file', '/tmp/tmp6i0c6mvn']
[2023-02-13 14:59:57,140] {standard_task_runner.py:80} INFO - Job 156: Subtask api_call
[2023-02-13 14:59:57,183] {task_command.py:369} INFO - Running <TaskInstance: branch_octavo_dag.api_call manual__2023-02-13T20:58:41.538479+00:00 [running]> on host Tinmar.
[2023-02-13 14:59:57,229] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=branch_octavo_dag
AIRFLOW_CTX_TASK_ID=api_call
AIRFLOW_CTX_EXECUTION_DATE=2023-02-13T20:58:41.538479+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-13T20:58:41.538479+00:00
[2023-02-13 14:59:57,230] {http.py:123} INFO - Calling HTTP method
[2023-02-13 14:59:57,239] {base.py:68} INFO - Using connection ID 'random_number' for task execution.
[2023-02-13 14:59:58,439] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=branch_octavo_dag, task_id=api_call, execution_date=20230213T205841, start_date=20230213T205957, end_date=20230213T205958
[2023-02-13 14:59:58,482] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-13 14:59:58,515] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
