[2023-02-20T09:18:19.267-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.create_table scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T09:18:19.319-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.create_table scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T09:18:19.328-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T09:18:19.350-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-20T09:18:19.353-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T09:18:19.388-0600] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-02-19 00:00:00+00:00
[2023-02-20T09:18:19.406-0600] {standard_task_runner.py:54} INFO - Started process 197660 to run task
[2023-02-20T09:18:19.428-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.6.1_user_processing', 'create_table', 'scheduled__2023-02-19T00:00:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6.1_user_processing.py', '--cfg-path', '/tmp/tmpe24kibw6']
[2023-02-20T09:18:19.440-0600] {standard_task_runner.py:83} INFO - Job 547: Subtask create_table
[2023-02-20T09:18:19.452-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.6.1_user_processing.py
[2023-02-20T09:18:21.486-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.6.1_user_processing.create_table scheduled__2023-02-19T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-20T09:18:21.952-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6.1_user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-19T00:00:00+00:00
[2023-02-20T09:18:21.953-0600] {sql.py:254} INFO - Executing: 
                                        CREATE TABLE IF NOT EXISTS users (
                                            firstname TEXT NOT NULL,
                                            lastname TEXT NOT NULL,
                                            country TEXT NOT NULL,
                                            username TEXT NOT NULL,
                                            password TEXT NOT NULL,
                                            email TEXT NOT NULL
                                        );
                                    
[2023-02-20T09:18:22.018-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-20T09:18:24.017-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-20T09:18:24.044-0600] {sql.py:375} INFO - Running statement: 
                                        CREATE TABLE IF NOT EXISTS users (
                                            firstname TEXT NOT NULL,
                                            lastname TEXT NOT NULL,
                                            country TEXT NOT NULL,
                                            username TEXT NOT NULL,
                                            password TEXT NOT NULL,
                                            email TEXT NOT NULL
                                        );
                                    , parameters: None
[2023-02-20T09:18:24.107-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.6.1_user_processing, task_id=create_table, execution_date=20230219T000000, start_date=20230220T151819, end_date=20230220T151824
[2023-02-20T09:18:24.271-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-20T09:18:24.359-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
