[2023-02-01 17:47:00,495] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-01-31T00:00:00+00:00 [queued]>
[2023-02-01 17:47:00,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-01-31T00:00:00+00:00 [queued]>
[2023-02-01 17:47:00,510] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-01 17:47:00,512] {taskinstance.py:1357} INFO - Starting attempt 7 of 7
[2023-02-01 17:47:00,512] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-01 17:47:00,540] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster> on 2023-01-31 00:00:00+00:00
[2023-02-01 17:47:00,542] {standard_task_runner.py:52} INFO - Started process 13844 to run task
[2023-02-01 17:47:00,544] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '6_dataproc_airflow', 'create_cluster', 'scheduled__2023-01-31T00:00:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/Airflow2_0_De_0_a_Heroe/6_dataproc_airflow.py', '--cfg-path', '/tmp/tmpphrmcuml', '--error-file', '/tmp/tmp6o5ubnp9']
[2023-02-01 17:47:00,545] {standard_task_runner.py:80} INFO - Job 132: Subtask create_cluster
[2023-02-01 17:47:00,604] {task_command.py:369} INFO - Running <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-01-31T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-01 17:47:00,727] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=David S
AIRFLOW_CTX_DAG_ID=6_dataproc_airflow
AIRFLOW_CTX_TASK_ID=create_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-31T00:00:00+00:00
[2023-02-01 17:47:00,728] {dataproc.py:591} INFO - Creating cluster: airflow-spark-cluster
[2023-02-01 17:47:00,742] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-01 17:49:31,269] {dataproc.py:535} INFO - Cluster created.
[2023-02-01 17:49:31,326] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=6_dataproc_airflow, task_id=create_cluster, execution_date=20230131T000000, start_date=20230201T234700, end_date=20230201T234931
[2023-02-01 17:49:31,380] {local_task_job.py:156} INFO - Task exited with return code 0
