[2023-02-17T12:25:25.813-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.is_api_available scheduled__2023-02-16T00:00:00+00:00 [queued]>
[2023-02-17T12:25:25.825-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.is_api_available scheduled__2023-02-16T00:00:00+00:00 [queued]>
[2023-02-17T12:25:25.825-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-17T12:25:25.827-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-17T12:25:25.828-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-17T12:25:25.838-0600] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-16 00:00:00+00:00
[2023-02-17T12:25:25.841-0600] {standard_task_runner.py:54} INFO - Started process 134287 to run task
[2023-02-17T12:25:25.843-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.6.1_user_processing', 'is_api_available', 'scheduled__2023-02-16T00:00:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6.1_user_processing.py', '--cfg-path', '/tmp/tmp1gl7frro']
[2023-02-17T12:25:25.845-0600] {standard_task_runner.py:83} INFO - Job 396: Subtask is_api_available
[2023-02-17T12:25:25.847-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.6.1_user_processing.py
[2023-02-17T12:25:26.135-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.6.1_user_processing.is_api_available scheduled__2023-02-16T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-17T12:25:26.184-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6.1_user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-16T00:00:00+00:00
[2023-02-17T12:25:26.185-0600] {http.py:122} INFO - Poking: api/
[2023-02-17T12:25:26.195-0600] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-02-17T12:25:26.602-0600] {base.py:213} INFO - Success criteria met. Exiting.
[2023-02-17T12:25:26.611-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.6.1_user_processing, task_id=is_api_available, execution_date=20230216T000000, start_date=20230217T182525, end_date=20230217T182526
[2023-02-17T12:25:26.652-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-17T12:25:26.674-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
