[2023-01-31 10:15:01,244] {processor.py:153} INFO - Started process (PID=173) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:01,245] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:15:01,245] {logging_mixin.py:115} INFO - [2023-01-31 10:15:01,245] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:01,522] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:15:01,536] {logging_mixin.py:115} INFO - [2023-01-31 10:15:01,526] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:15:01,539] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:01,584] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.341 seconds
[2023-01-31 10:15:32,407] {processor.py:153} INFO - Started process (PID=193) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:32,409] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:15:32,410] {logging_mixin.py:115} INFO - [2023-01-31 10:15:32,410] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:32,637] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:15:32,649] {logging_mixin.py:115} INFO - [2023-01-31 10:15:32,639] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:15:32,652] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:15:32,691] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.286 seconds
[2023-01-31 10:16:13,190] {processor.py:153} INFO - Started process (PID=231) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:13,190] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:16:13,191] {logging_mixin.py:115} INFO - [2023-01-31 10:16:13,191] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:13,418] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:16:13,426] {logging_mixin.py:115} INFO - [2023-01-31 10:16:13,419] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:16:13,427] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:13,456] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.269 seconds
[2023-01-31 10:16:43,513] {processor.py:153} INFO - Started process (PID=251) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:43,513] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:16:43,514] {logging_mixin.py:115} INFO - [2023-01-31 10:16:43,514] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:43,727] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:16:43,735] {logging_mixin.py:115} INFO - [2023-01-31 10:16:43,728] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:16:43,737] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:16:43,766] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.255 seconds
[2023-01-31 10:17:14,293] {processor.py:153} INFO - Started process (PID=271) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:14,293] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:17:14,294] {logging_mixin.py:115} INFO - [2023-01-31 10:17:14,294] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:14,560] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:17:14,572] {logging_mixin.py:115} INFO - [2023-01-31 10:17:14,561] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:17:14,576] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:14,638] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.348 seconds
[2023-01-31 10:17:44,720] {processor.py:153} INFO - Started process (PID=291) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:44,721] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:17:44,722] {logging_mixin.py:115} INFO - [2023-01-31 10:17:44,721] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:44,964] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:17:44,972] {logging_mixin.py:115} INFO - [2023-01-31 10:17:44,965] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:17:44,974] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:17:45,006] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.288 seconds
[2023-01-31 10:18:15,825] {processor.py:153} INFO - Started process (PID=311) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:15,825] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:18:15,826] {logging_mixin.py:115} INFO - [2023-01-31 10:18:15,826] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:16,034] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:18:16,042] {logging_mixin.py:115} INFO - [2023-01-31 10:18:16,035] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:18:16,044] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:16,084] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.262 seconds
[2023-01-31 10:18:46,824] {processor.py:153} INFO - Started process (PID=331) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:46,825] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:18:46,826] {logging_mixin.py:115} INFO - [2023-01-31 10:18:46,826] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:47,027] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:18:47,037] {logging_mixin.py:115} INFO - [2023-01-31 10:18:47,029] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:18:47,039] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:18:47,069] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.247 seconds
[2023-01-31 10:19:17,788] {processor.py:153} INFO - Started process (PID=351) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:17,789] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:19:17,790] {logging_mixin.py:115} INFO - [2023-01-31 10:19:17,789] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:18,029] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:19:18,040] {logging_mixin.py:115} INFO - [2023-01-31 10:19:18,030] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:19:18,043] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:18,077] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.291 seconds
[2023-01-31 10:19:48,218] {processor.py:153} INFO - Started process (PID=371) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:48,219] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:19:48,219] {logging_mixin.py:115} INFO - [2023-01-31 10:19:48,219] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:48,434] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:19:48,445] {logging_mixin.py:115} INFO - [2023-01-31 10:19:48,436] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:19:48,450] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:19:48,503] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.286 seconds
[2023-01-31 10:20:18,744] {processor.py:153} INFO - Started process (PID=391) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:18,745] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:20:18,746] {logging_mixin.py:115} INFO - [2023-01-31 10:20:18,746] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:18,956] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:20:18,967] {logging_mixin.py:115} INFO - [2023-01-31 10:20:18,957] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:20:18,971] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:19,002] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.260 seconds
[2023-01-31 10:20:49,937] {processor.py:153} INFO - Started process (PID=411) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:49,938] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:20:49,938] {logging_mixin.py:115} INFO - [2023-01-31 10:20:49,938] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:50,157] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:20:50,163] {logging_mixin.py:115} INFO - [2023-01-31 10:20:50,158] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:20:50,165] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:20:50,195] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.260 seconds
[2023-01-31 10:21:20,683] {processor.py:153} INFO - Started process (PID=449) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:20,684] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:21:20,685] {logging_mixin.py:115} INFO - [2023-01-31 10:21:20,685] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:20,917] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:21:20,925] {logging_mixin.py:115} INFO - [2023-01-31 10:21:20,918] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:21:20,928] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:20,960] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.279 seconds
[2023-01-31 10:21:51,627] {processor.py:153} INFO - Started process (PID=469) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:51,627] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:21:51,628] {logging_mixin.py:115} INFO - [2023-01-31 10:21:51,628] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:51,846] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:21:51,858] {logging_mixin.py:115} INFO - [2023-01-31 10:21:51,847] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:21:51,861] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:21:51,903] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.278 seconds
[2023-01-31 10:22:22,387] {processor.py:153} INFO - Started process (PID=489) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:22,388] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:22:22,389] {logging_mixin.py:115} INFO - [2023-01-31 10:22:22,389] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:22,618] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:22:22,629] {logging_mixin.py:115} INFO - [2023-01-31 10:22:22,620] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:22:22,631] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:22,663] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.278 seconds
[2023-01-31 10:22:53,046] {processor.py:153} INFO - Started process (PID=509) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:53,047] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:22:53,047] {logging_mixin.py:115} INFO - [2023-01-31 10:22:53,047] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:53,264] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:22:53,270] {logging_mixin.py:115} INFO - [2023-01-31 10:22:53,265] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:22:53,272] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:22:53,306] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.261 seconds
[2023-01-31 10:23:24,618] {processor.py:153} INFO - Started process (PID=547) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:24,618] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:23:24,619] {logging_mixin.py:115} INFO - [2023-01-31 10:23:24,619] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:24,843] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:23:24,852] {logging_mixin.py:115} INFO - [2023-01-31 10:23:24,845] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:23:24,854] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:24,886] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.270 seconds
[2023-01-31 10:23:55,222] {processor.py:153} INFO - Started process (PID=567) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:55,222] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:23:55,223] {logging_mixin.py:115} INFO - [2023-01-31 10:23:55,223] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:55,430] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:23:55,438] {logging_mixin.py:115} INFO - [2023-01-31 10:23:55,431] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:23:55,440] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:23:55,466] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.246 seconds
[2023-01-31 10:24:26,012] {processor.py:153} INFO - Started process (PID=587) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:26,012] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:24:26,013] {logging_mixin.py:115} INFO - [2023-01-31 10:24:26,013] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:26,212] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:24:26,219] {logging_mixin.py:115} INFO - [2023-01-31 10:24:26,213] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:24:26,221] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:26,250] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.240 seconds
[2023-01-31 10:24:56,658] {processor.py:153} INFO - Started process (PID=607) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:56,659] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:24:56,660] {logging_mixin.py:115} INFO - [2023-01-31 10:24:56,660] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:56,860] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:24:56,866] {logging_mixin.py:115} INFO - [2023-01-31 10:24:56,861] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:24:56,868] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:24:56,899] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.243 seconds
[2023-01-31 10:25:27,038] {processor.py:153} INFO - Started process (PID=627) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:27,039] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:25:27,040] {logging_mixin.py:115} INFO - [2023-01-31 10:25:27,039] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:27,250] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:25:27,257] {logging_mixin.py:115} INFO - [2023-01-31 10:25:27,251] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:25:27,259] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:27,286] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.249 seconds
[2023-01-31 10:25:58,018] {processor.py:153} INFO - Started process (PID=647) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:58,018] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:25:58,019] {logging_mixin.py:115} INFO - [2023-01-31 10:25:58,019] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:58,223] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:25:58,229] {logging_mixin.py:115} INFO - [2023-01-31 10:25:58,224] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:25:58,231] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:25:58,269] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.253 seconds
[2023-01-31 10:26:29,006] {processor.py:153} INFO - Started process (PID=667) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:26:29,006] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:26:29,007] {logging_mixin.py:115} INFO - [2023-01-31 10:26:29,007] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:26:29,205] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:26:29,211] {logging_mixin.py:115} INFO - [2023-01-31 10:26:29,206] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:26:29,213] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:26:29,245] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.241 seconds
[2023-01-31 10:27:00,296] {processor.py:153} INFO - Started process (PID=687) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:00,298] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:27:00,298] {logging_mixin.py:115} INFO - [2023-01-31 10:27:00,298] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:00,529] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:27:00,535] {logging_mixin.py:115} INFO - [2023-01-31 10:27:00,530] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:27:00,537] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:00,571] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.277 seconds
[2023-01-31 10:27:31,399] {processor.py:153} INFO - Started process (PID=707) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:31,399] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:27:31,400] {logging_mixin.py:115} INFO - [2023-01-31 10:27:31,400] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:31,603] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:27:31,611] {logging_mixin.py:115} INFO - [2023-01-31 10:27:31,604] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:27:31,613] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:27:31,640] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.243 seconds
[2023-01-31 10:28:02,401] {processor.py:153} INFO - Started process (PID=727) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:02,401] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:28:02,402] {logging_mixin.py:115} INFO - [2023-01-31 10:28:02,402] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:02,609] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:28:02,616] {logging_mixin.py:115} INFO - [2023-01-31 10:28:02,610] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:28:02,618] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:02,651] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.252 seconds
[2023-01-31 10:28:34,506] {processor.py:153} INFO - Started process (PID=747) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:34,507] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:28:34,507] {logging_mixin.py:115} INFO - [2023-01-31 10:28:34,507] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:34,711] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:28:34,717] {logging_mixin.py:115} INFO - [2023-01-31 10:28:34,712] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:28:34,719] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:28:34,751] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.247 seconds
[2023-01-31 10:29:15,469] {processor.py:153} INFO - Started process (PID=803) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:15,470] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:29:15,470] {logging_mixin.py:115} INFO - [2023-01-31 10:29:15,470] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:15,671] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:29:15,679] {logging_mixin.py:115} INFO - [2023-01-31 10:29:15,672] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:29:15,681] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:15,708] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.241 seconds
[2023-01-31 10:29:46,501] {processor.py:153} INFO - Started process (PID=823) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:46,502] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:29:46,503] {logging_mixin.py:115} INFO - [2023-01-31 10:29:46,503] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:46,715] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:29:46,727] {logging_mixin.py:115} INFO - [2023-01-31 10:29:46,716] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:29:46,730] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:29:46,763] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.263 seconds
[2023-01-31 10:30:17,366] {processor.py:153} INFO - Started process (PID=843) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:17,367] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:30:17,368] {logging_mixin.py:115} INFO - [2023-01-31 10:30:17,368] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:17,596] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:30:17,608] {logging_mixin.py:115} INFO - [2023-01-31 10:30:17,598] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:30:17,610] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:17,639] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.274 seconds
[2023-01-31 10:30:48,160] {processor.py:153} INFO - Started process (PID=863) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:48,160] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:30:48,161] {logging_mixin.py:115} INFO - [2023-01-31 10:30:48,161] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:48,397] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:30:48,404] {logging_mixin.py:115} INFO - [2023-01-31 10:30:48,398] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:30:48,406] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:30:48,442] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.284 seconds
[2023-01-31 10:31:19,073] {processor.py:153} INFO - Started process (PID=883) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:19,074] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:31:19,075] {logging_mixin.py:115} INFO - [2023-01-31 10:31:19,075] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:19,284] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:31:19,292] {logging_mixin.py:115} INFO - [2023-01-31 10:31:19,285] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:31:19,294] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:19,324] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.252 seconds
[2023-01-31 10:31:49,930] {processor.py:153} INFO - Started process (PID=903) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:49,931] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:31:49,931] {logging_mixin.py:115} INFO - [2023-01-31 10:31:49,931] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:50,136] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:31:50,143] {logging_mixin.py:115} INFO - [2023-01-31 10:31:50,137] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:31:50,145] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:31:50,175] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.247 seconds
[2023-01-31 10:32:20,758] {processor.py:153} INFO - Started process (PID=923) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:20,759] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:32:20,759] {logging_mixin.py:115} INFO - [2023-01-31 10:32:20,759] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:20,977] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:32:20,987] {logging_mixin.py:115} INFO - [2023-01-31 10:32:20,978] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:32:20,989] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:21,020] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.264 seconds
[2023-01-31 10:32:51,655] {processor.py:153} INFO - Started process (PID=943) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:51,656] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:32:51,657] {logging_mixin.py:115} INFO - [2023-01-31 10:32:51,657] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:51,876] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:32:51,892] {logging_mixin.py:115} INFO - [2023-01-31 10:32:51,877] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:32:51,895] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:32:51,922] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.268 seconds
[2023-01-31 10:33:22,478] {processor.py:153} INFO - Started process (PID=963) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:22,478] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:33:22,479] {logging_mixin.py:115} INFO - [2023-01-31 10:33:22,479] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:22,692] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:33:22,718] {logging_mixin.py:115} INFO - [2023-01-31 10:33:22,711] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:33:22,720] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:22,747] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.271 seconds
[2023-01-31 10:33:53,364] {processor.py:153} INFO - Started process (PID=983) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:53,364] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:33:53,365] {logging_mixin.py:115} INFO - [2023-01-31 10:33:53,365] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:53,590] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:33:53,597] {logging_mixin.py:115} INFO - [2023-01-31 10:33:53,591] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:33:53,600] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:33:53,630] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.268 seconds
[2023-01-31 10:34:24,407] {processor.py:153} INFO - Started process (PID=1003) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:24,408] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:34:24,409] {logging_mixin.py:115} INFO - [2023-01-31 10:34:24,408] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:24,636] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:34:24,643] {logging_mixin.py:115} INFO - [2023-01-31 10:34:24,638] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:34:24,646] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:24,676] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.270 seconds
[2023-01-31 10:34:55,718] {processor.py:153} INFO - Started process (PID=1023) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:55,718] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:34:55,719] {logging_mixin.py:115} INFO - [2023-01-31 10:34:55,719] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:55,937] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:34:55,944] {logging_mixin.py:115} INFO - [2023-01-31 10:34:55,938] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:34:55,946] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:34:55,973] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.257 seconds
[2023-01-31 10:35:26,599] {processor.py:153} INFO - Started process (PID=1043) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:26,600] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:35:26,600] {logging_mixin.py:115} INFO - [2023-01-31 10:35:26,600] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:26,818] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:35:26,826] {logging_mixin.py:115} INFO - [2023-01-31 10:35:26,819] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:35:26,827] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:26,858] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.261 seconds
[2023-01-31 10:35:57,453] {processor.py:153} INFO - Started process (PID=1063) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:57,454] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:35:57,455] {logging_mixin.py:115} INFO - [2023-01-31 10:35:57,454] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:57,668] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:35:57,676] {logging_mixin.py:115} INFO - [2023-01-31 10:35:57,669] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:35:57,678] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:35:57,726] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.274 seconds
[2023-01-31 10:36:28,510] {processor.py:153} INFO - Started process (PID=1083) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:28,510] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:36:28,511] {logging_mixin.py:115} INFO - [2023-01-31 10:36:28,511] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:28,737] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:36:28,745] {logging_mixin.py:115} INFO - [2023-01-31 10:36:28,739] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:36:28,747] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:28,780] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.272 seconds
[2023-01-31 10:36:59,340] {processor.py:153} INFO - Started process (PID=1103) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:59,340] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:36:59,341] {logging_mixin.py:115} INFO - [2023-01-31 10:36:59,341] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:59,546] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:36:59,553] {logging_mixin.py:115} INFO - [2023-01-31 10:36:59,547] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:36:59,555] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:36:59,587] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.249 seconds
[2023-01-31 10:37:30,131] {processor.py:153} INFO - Started process (PID=1122) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:37:30,132] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:37:30,132] {logging_mixin.py:115} INFO - [2023-01-31 10:37:30,132] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:37:30,350] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:37:30,361] {logging_mixin.py:115} INFO - [2023-01-31 10:37:30,351] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:37:30,363] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:37:30,390] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.261 seconds
[2023-01-31 10:38:00,973] {processor.py:153} INFO - Started process (PID=1142) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:00,973] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:38:00,974] {logging_mixin.py:115} INFO - [2023-01-31 10:38:00,974] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:01,191] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:38:01,198] {logging_mixin.py:115} INFO - [2023-01-31 10:38:01,192] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:38:01,199] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:01,247] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.276 seconds
[2023-01-31 10:38:31,801] {processor.py:153} INFO - Started process (PID=1162) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:31,802] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:38:31,802] {logging_mixin.py:115} INFO - [2023-01-31 10:38:31,802] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:32,042] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:38:32,050] {logging_mixin.py:115} INFO - [2023-01-31 10:38:32,043] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:38:32,053] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:38:32,090] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.290 seconds
[2023-01-31 10:39:02,662] {processor.py:153} INFO - Started process (PID=1182) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:02,663] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:39:02,663] {logging_mixin.py:115} INFO - [2023-01-31 10:39:02,663] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:02,901] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:39:02,909] {logging_mixin.py:115} INFO - [2023-01-31 10:39:02,902] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:39:02,910] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:02,944] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.284 seconds
[2023-01-31 10:39:33,610] {processor.py:153} INFO - Started process (PID=1202) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:33,611] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:39:33,611] {logging_mixin.py:115} INFO - [2023-01-31 10:39:33,611] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:33,822] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:39:33,838] {logging_mixin.py:115} INFO - [2023-01-31 10:39:33,823] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:39:33,841] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:39:33,871] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.263 seconds
[2023-01-31 10:40:13,362] {processor.py:153} INFO - Started process (PID=1296) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:13,363] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:40:13,363] {logging_mixin.py:115} INFO - [2023-01-31 10:40:13,363] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:13,616] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:40:13,626] {logging_mixin.py:115} INFO - [2023-01-31 10:40:13,617] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:40:13,628] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:13,664] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.303 seconds
[2023-01-31 10:40:44,025] {processor.py:153} INFO - Started process (PID=1316) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:44,025] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:40:44,026] {logging_mixin.py:115} INFO - [2023-01-31 10:40:44,026] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:44,233] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:40:44,241] {logging_mixin.py:115} INFO - [2023-01-31 10:40:44,234] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:40:44,242] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:40:44,271] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.248 seconds
[2023-01-31 10:41:15,134] {processor.py:153} INFO - Started process (PID=1336) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:15,135] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:41:15,135] {logging_mixin.py:115} INFO - [2023-01-31 10:41:15,135] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:15,373] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:41:15,383] {logging_mixin.py:115} INFO - [2023-01-31 10:41:15,375] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:41:15,385] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:15,417] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.285 seconds
[2023-01-31 10:41:45,648] {processor.py:153} INFO - Started process (PID=1356) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:45,649] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:41:45,649] {logging_mixin.py:115} INFO - [2023-01-31 10:41:45,649] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:45,859] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:41:45,869] {logging_mixin.py:115} INFO - [2023-01-31 10:41:45,860] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:41:45,871] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:41:45,899] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.252 seconds
[2023-01-31 10:42:16,375] {processor.py:153} INFO - Started process (PID=1376) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:16,376] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:42:16,377] {logging_mixin.py:115} INFO - [2023-01-31 10:42:16,377] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:16,597] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:42:16,607] {logging_mixin.py:115} INFO - [2023-01-31 10:42:16,598] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:42:16,610] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:16,639] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.265 seconds
[2023-01-31 10:42:51,133] {processor.py:153} INFO - Started process (PID=1468) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:51,134] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:42:51,134] {logging_mixin.py:115} INFO - [2023-01-31 10:42:51,134] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:51,340] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:42:51,349] {logging_mixin.py:115} INFO - [2023-01-31 10:42:51,341] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:42:51,350] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:42:51,377] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.246 seconds
[2023-01-31 10:43:22,440] {processor.py:153} INFO - Started process (PID=1488) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:22,440] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:43:22,441] {logging_mixin.py:115} INFO - [2023-01-31 10:43:22,441] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:22,650] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:43:22,658] {logging_mixin.py:115} INFO - [2023-01-31 10:43:22,651] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:43:22,660] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:22,707] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.270 seconds
[2023-01-31 10:43:53,616] {processor.py:153} INFO - Started process (PID=1508) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:53,617] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:43:53,620] {logging_mixin.py:115} INFO - [2023-01-31 10:43:53,620] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:53,886] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:43:53,898] {logging_mixin.py:115} INFO - [2023-01-31 10:43:53,887] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:43:53,901] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:43:53,977] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.363 seconds
[2023-01-31 10:44:25,410] {processor.py:153} INFO - Started process (PID=1600) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:25,410] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:44:25,411] {logging_mixin.py:115} INFO - [2023-01-31 10:44:25,411] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:25,662] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:44:25,672] {logging_mixin.py:115} INFO - [2023-01-31 10:44:25,664] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:44:25,674] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:25,706] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.298 seconds
[2023-01-31 10:44:57,073] {processor.py:153} INFO - Started process (PID=1620) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:57,074] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:44:57,074] {logging_mixin.py:115} INFO - [2023-01-31 10:44:57,074] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:57,291] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:44:57,299] {logging_mixin.py:115} INFO - [2023-01-31 10:44:57,292] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:44:57,301] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:44:57,328] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.257 seconds
[2023-01-31 10:45:28,560] {processor.py:153} INFO - Started process (PID=1640) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:45:28,561] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:45:28,562] {logging_mixin.py:115} INFO - [2023-01-31 10:45:28,562] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:45:28,783] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:45:28,789] {logging_mixin.py:115} INFO - [2023-01-31 10:45:28,784] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:45:28,791] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:45:28,824] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.266 seconds
[2023-01-31 10:45:59,746] {processor.py:153} INFO - Started process (PID=1660) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:45:59,747] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:45:59,747] {logging_mixin.py:115} INFO - [2023-01-31 10:45:59,747] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:45:59,982] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:45:59,994] {logging_mixin.py:115} INFO - [2023-01-31 10:45:59,984] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:45:59,998] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:46:00,051] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.307 seconds
[2023-01-31 10:46:30,809] {processor.py:153} INFO - Started process (PID=1680) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:46:30,810] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:46:30,810] {logging_mixin.py:115} INFO - [2023-01-31 10:46:30,810] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:46:31,030] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:46:31,041] {logging_mixin.py:115} INFO - [2023-01-31 10:46:31,031] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:46:31,043] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:46:31,075] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.268 seconds
[2023-01-31 10:47:21,311] {processor.py:153} INFO - Started process (PID=1773) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:21,312] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:47:21,313] {logging_mixin.py:115} INFO - [2023-01-31 10:47:21,313] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:21,553] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:47:21,561] {logging_mixin.py:115} INFO - [2023-01-31 10:47:21,554] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:47:21,563] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:21,595] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.286 seconds
[2023-01-31 10:47:53,076] {processor.py:153} INFO - Started process (PID=1793) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:53,077] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:47:53,077] {logging_mixin.py:115} INFO - [2023-01-31 10:47:53,077] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:53,310] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:47:53,322] {logging_mixin.py:115} INFO - [2023-01-31 10:47:53,311] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:47:53,325] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:47:53,356] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.282 seconds
[2023-01-31 10:48:24,239] {processor.py:153} INFO - Started process (PID=1813) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:24,239] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:48:24,240] {logging_mixin.py:115} INFO - [2023-01-31 10:48:24,240] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:24,481] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:48:24,488] {logging_mixin.py:115} INFO - [2023-01-31 10:48:24,482] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:48:24,491] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:24,523] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.286 seconds
[2023-01-31 10:48:55,248] {processor.py:153} INFO - Started process (PID=1833) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:55,248] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:48:55,249] {logging_mixin.py:115} INFO - [2023-01-31 10:48:55,249] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:55,458] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:48:55,466] {logging_mixin.py:115} INFO - [2023-01-31 10:48:55,460] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:48:55,470] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:48:55,506] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.260 seconds
[2023-01-31 10:49:26,834] {processor.py:153} INFO - Started process (PID=1853) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:26,834] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:49:26,835] {logging_mixin.py:115} INFO - [2023-01-31 10:49:26,835] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:27,056] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:49:27,066] {logging_mixin.py:115} INFO - [2023-01-31 10:49:27,058] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:49:27,069] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:27,100] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.268 seconds
[2023-01-31 10:49:58,434] {processor.py:153} INFO - Started process (PID=1873) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:58,435] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:49:58,436] {logging_mixin.py:115} INFO - [2023-01-31 10:49:58,436] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:58,665] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:49:58,673] {logging_mixin.py:115} INFO - [2023-01-31 10:49:58,666] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:49:58,675] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:49:58,708] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.276 seconds
[2023-01-31 10:50:29,949] {processor.py:153} INFO - Started process (PID=1893) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:50:29,950] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:50:29,950] {logging_mixin.py:115} INFO - [2023-01-31 10:50:29,950] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:50:30,171] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:50:30,179] {logging_mixin.py:115} INFO - [2023-01-31 10:50:30,172] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:50:30,181] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:50:30,215] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.267 seconds
[2023-01-31 10:51:01,308] {processor.py:153} INFO - Started process (PID=1913) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:01,309] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:51:01,310] {logging_mixin.py:115} INFO - [2023-01-31 10:51:01,310] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:01,547] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:51:01,559] {logging_mixin.py:115} INFO - [2023-01-31 10:51:01,548] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:51:01,562] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:01,599] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.293 seconds
[2023-01-31 10:51:33,125] {processor.py:153} INFO - Started process (PID=1933) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:33,127] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:51:33,127] {logging_mixin.py:115} INFO - [2023-01-31 10:51:33,127] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:33,348] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:51:33,356] {logging_mixin.py:115} INFO - [2023-01-31 10:51:33,349] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:51:33,357] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:51:33,393] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.269 seconds
[2023-01-31 10:52:04,640] {processor.py:153} INFO - Started process (PID=1953) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:04,640] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:52:04,641] {logging_mixin.py:115} INFO - [2023-01-31 10:52:04,641] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:04,861] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:52:04,869] {logging_mixin.py:115} INFO - [2023-01-31 10:52:04,862] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:52:04,872] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:04,904] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.266 seconds
[2023-01-31 10:52:35,792] {processor.py:153} INFO - Started process (PID=1973) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:35,792] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:52:35,793] {logging_mixin.py:115} INFO - [2023-01-31 10:52:35,793] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:36,015] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:52:36,024] {logging_mixin.py:115} INFO - [2023-01-31 10:52:36,017] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:52:36,026] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:52:36,063] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.273 seconds
[2023-01-31 10:53:07,080] {processor.py:153} INFO - Started process (PID=1993) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:07,081] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:53:07,081] {logging_mixin.py:115} INFO - [2023-01-31 10:53:07,081] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:07,296] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:53:07,304] {logging_mixin.py:115} INFO - [2023-01-31 10:53:07,297] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:53:07,307] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:07,335] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.257 seconds
[2023-01-31 10:53:38,428] {processor.py:153} INFO - Started process (PID=2013) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:38,428] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:53:38,429] {logging_mixin.py:115} INFO - [2023-01-31 10:53:38,429] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:38,650] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:53:38,657] {logging_mixin.py:115} INFO - [2023-01-31 10:53:38,651] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:53:38,659] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:53:38,687] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.261 seconds
[2023-01-31 10:54:09,442] {processor.py:153} INFO - Started process (PID=2033) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:09,443] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:54:09,443] {logging_mixin.py:115} INFO - [2023-01-31 10:54:09,443] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:09,658] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:54:09,665] {logging_mixin.py:115} INFO - [2023-01-31 10:54:09,659] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:54:09,668] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:09,702] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.261 seconds
[2023-01-31 10:54:40,473] {processor.py:153} INFO - Started process (PID=2053) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:40,474] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:54:40,475] {logging_mixin.py:115} INFO - [2023-01-31 10:54:40,475] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:40,689] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:54:40,696] {logging_mixin.py:115} INFO - [2023-01-31 10:54:40,690] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:54:40,698] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:54:40,734] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.262 seconds
[2023-01-31 10:55:11,632] {processor.py:153} INFO - Started process (PID=2073) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:11,633] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:55:11,634] {logging_mixin.py:115} INFO - [2023-01-31 10:55:11,633] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:11,860] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:55:11,868] {logging_mixin.py:115} INFO - [2023-01-31 10:55:11,861] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:55:11,870] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:11,903] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.272 seconds
[2023-01-31 10:55:42,782] {processor.py:153} INFO - Started process (PID=2093) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:42,782] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:55:42,783] {logging_mixin.py:115} INFO - [2023-01-31 10:55:42,783] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:43,001] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:55:43,011] {logging_mixin.py:115} INFO - [2023-01-31 10:55:43,002] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:55:43,013] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:55:43,051] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.272 seconds
[2023-01-31 10:56:13,969] {processor.py:153} INFO - Started process (PID=2113) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:13,970] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:56:13,971] {logging_mixin.py:115} INFO - [2023-01-31 10:56:13,971] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:14,213] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:56:14,221] {logging_mixin.py:115} INFO - [2023-01-31 10:56:14,214] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:56:14,223] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:14,264] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.296 seconds
[2023-01-31 10:56:45,249] {processor.py:153} INFO - Started process (PID=2133) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:45,250] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:56:45,251] {logging_mixin.py:115} INFO - [2023-01-31 10:56:45,250] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:45,471] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:56:45,480] {logging_mixin.py:115} INFO - [2023-01-31 10:56:45,472] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:56:45,482] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:56:45,517] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.269 seconds
[2023-01-31 10:57:16,353] {processor.py:153} INFO - Started process (PID=2153) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:16,354] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:57:16,354] {logging_mixin.py:115} INFO - [2023-01-31 10:57:16,354] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:16,563] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:57:16,572] {logging_mixin.py:115} INFO - [2023-01-31 10:57:16,564] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:57:16,574] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:16,606] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.255 seconds
[2023-01-31 10:57:47,691] {processor.py:153} INFO - Started process (PID=2173) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:47,691] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:57:47,692] {logging_mixin.py:115} INFO - [2023-01-31 10:57:47,692] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:47,913] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:57:47,924] {logging_mixin.py:115} INFO - [2023-01-31 10:57:47,914] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:57:47,926] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:57:47,958] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.269 seconds
[2023-01-31 10:58:18,960] {processor.py:153} INFO - Started process (PID=2193) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:18,961] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:58:18,962] {logging_mixin.py:115} INFO - [2023-01-31 10:58:18,961] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:19,165] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:58:19,172] {logging_mixin.py:115} INFO - [2023-01-31 10:58:19,166] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:58:19,174] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:19,205] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.247 seconds
[2023-01-31 10:58:50,273] {processor.py:153} INFO - Started process (PID=2213) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:50,273] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:58:50,274] {logging_mixin.py:115} INFO - [2023-01-31 10:58:50,274] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:50,472] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:58:50,481] {logging_mixin.py:115} INFO - [2023-01-31 10:58:50,473] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:58:50,483] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:58:50,517] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.246 seconds
[2023-01-31 10:59:21,612] {processor.py:153} INFO - Started process (PID=2233) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:21,613] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:59:21,613] {logging_mixin.py:115} INFO - [2023-01-31 10:59:21,613] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:21,832] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:59:21,839] {logging_mixin.py:115} INFO - [2023-01-31 10:59:21,833] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:59:21,840] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:21,867] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.257 seconds
[2023-01-31 10:59:52,921] {processor.py:153} INFO - Started process (PID=2253) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:52,921] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 10:59:52,922] {logging_mixin.py:115} INFO - [2023-01-31 10:59:52,922] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:53,136] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 10:59:53,144] {logging_mixin.py:115} INFO - [2023-01-31 10:59:53,137] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 10:59:53,146] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 10:59:53,175] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.256 seconds
[2023-01-31 11:00:24,259] {processor.py:153} INFO - Started process (PID=2273) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:24,260] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:00:24,260] {logging_mixin.py:115} INFO - [2023-01-31 11:00:24,260] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:24,476] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:00:24,484] {logging_mixin.py:115} INFO - [2023-01-31 11:00:24,477] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:00:24,486] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:24,519] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.262 seconds
[2023-01-31 11:00:55,494] {processor.py:153} INFO - Started process (PID=2293) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:55,495] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:00:55,496] {logging_mixin.py:115} INFO - [2023-01-31 11:00:55,496] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:55,699] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:00:55,707] {logging_mixin.py:115} INFO - [2023-01-31 11:00:55,700] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:00:55,709] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:00:55,745] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.252 seconds
[2023-01-31 11:01:26,703] {processor.py:153} INFO - Started process (PID=2313) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:26,704] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:01:26,705] {logging_mixin.py:115} INFO - [2023-01-31 11:01:26,705] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:26,935] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:01:26,943] {logging_mixin.py:115} INFO - [2023-01-31 11:01:26,936] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:01:26,945] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:26,972] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.271 seconds
[2023-01-31 11:01:58,123] {processor.py:153} INFO - Started process (PID=2333) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:58,124] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:01:58,125] {logging_mixin.py:115} INFO - [2023-01-31 11:01:58,124] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:58,326] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:01:58,333] {logging_mixin.py:115} INFO - [2023-01-31 11:01:58,327] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:01:58,335] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:01:58,369] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.248 seconds
[2023-01-31 11:02:29,445] {processor.py:153} INFO - Started process (PID=2353) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:02:29,445] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:02:29,446] {logging_mixin.py:115} INFO - [2023-01-31 11:02:29,446] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:02:29,650] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:02:29,657] {logging_mixin.py:115} INFO - [2023-01-31 11:02:29,651] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:02:29,658] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:02:29,692] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.249 seconds
[2023-01-31 11:03:00,760] {processor.py:153} INFO - Started process (PID=2373) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:00,761] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:03:00,762] {logging_mixin.py:115} INFO - [2023-01-31 11:03:00,762] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:00,967] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:03:00,974] {logging_mixin.py:115} INFO - [2023-01-31 11:03:00,968] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:03:00,976] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:01,010] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.251 seconds
[2023-01-31 11:03:31,776] {processor.py:153} INFO - Started process (PID=2393) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:31,777] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:03:31,777] {logging_mixin.py:115} INFO - [2023-01-31 11:03:31,777] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:31,986] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:03:31,995] {logging_mixin.py:115} INFO - [2023-01-31 11:03:31,987] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:03:31,996] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:03:32,028] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.254 seconds
[2023-01-31 11:04:03,088] {processor.py:153} INFO - Started process (PID=2413) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:03,089] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:04:03,090] {logging_mixin.py:115} INFO - [2023-01-31 11:04:03,090] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:03,299] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:04:03,305] {logging_mixin.py:115} INFO - [2023-01-31 11:04:03,300] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:04:03,307] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:03,347] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.260 seconds
[2023-01-31 11:04:34,381] {processor.py:153} INFO - Started process (PID=2433) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:34,382] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:04:34,382] {logging_mixin.py:115} INFO - [2023-01-31 11:04:34,382] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:34,586] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:04:34,592] {logging_mixin.py:115} INFO - [2023-01-31 11:04:34,587] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:04:34,594] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:04:34,628] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.249 seconds
[2023-01-31 11:05:05,796] {processor.py:153} INFO - Started process (PID=2453) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:05,797] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:05:05,798] {logging_mixin.py:115} INFO - [2023-01-31 11:05:05,798] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:06,008] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:05:06,016] {logging_mixin.py:115} INFO - [2023-01-31 11:05:06,009] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:05:06,018] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:06,050] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.256 seconds
[2023-01-31 11:05:37,037] {processor.py:153} INFO - Started process (PID=2473) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:37,038] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:05:37,039] {logging_mixin.py:115} INFO - [2023-01-31 11:05:37,039] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:37,241] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:05:37,248] {logging_mixin.py:115} INFO - [2023-01-31 11:05:37,242] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:05:37,250] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:05:37,284] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.248 seconds
[2023-01-31 11:06:08,374] {processor.py:153} INFO - Started process (PID=2493) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:08,375] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:06:08,376] {logging_mixin.py:115} INFO - [2023-01-31 11:06:08,375] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:08,574] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:06:08,581] {logging_mixin.py:115} INFO - [2023-01-31 11:06:08,575] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:06:08,583] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:08,617] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.245 seconds
[2023-01-31 11:06:42,100] {processor.py:153} INFO - Started process (PID=2515) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:42,100] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:06:42,101] {logging_mixin.py:115} INFO - [2023-01-31 11:06:42,101] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:42,343] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:06:42,353] {logging_mixin.py:115} INFO - [2023-01-31 11:06:42,344] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:06:42,356] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:06:42,393] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.295 seconds
[2023-01-31 11:07:13,247] {processor.py:153} INFO - Started process (PID=2535) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:13,248] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:07:13,249] {logging_mixin.py:115} INFO - [2023-01-31 11:07:13,249] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:13,472] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:07:13,480] {logging_mixin.py:115} INFO - [2023-01-31 11:07:13,474] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:07:13,482] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:13,517] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.272 seconds
[2023-01-31 11:07:55,512] {processor.py:153} INFO - Started process (PID=2557) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:55,513] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:07:55,514] {logging_mixin.py:115} INFO - [2023-01-31 11:07:55,513] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:55,734] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:07:55,742] {logging_mixin.py:115} INFO - [2023-01-31 11:07:55,735] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:07:55,745] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:07:55,800] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.290 seconds
[2023-01-31 11:08:32,452] {processor.py:153} INFO - Started process (PID=2577) to work on /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:08:32,453] {processor.py:641} INFO - Processing file /c/Airflow/dags/6_dataproc_airflow.py for tasks to queue
[2023-01-31 11:08:32,454] {logging_mixin.py:115} INFO - [2023-01-31 11:08:32,454] {dagbag.py:507} INFO - Filling up the DagBag from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:08:33,121] {logging_mixin.py:115} WARNING - /home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py:390 DeprecationWarning: Passing cluster parameters by keywords to `DataprocCreateClusterOperator` will be deprecated. Please provide cluster_config object using `cluster_config` parameter. You can use `airflow.dataproc.ClusterGenerator.generate_cluster` method to obtain cluster object.
[2023-01-31 11:08:33,228] {logging_mixin.py:115} INFO - [2023-01-31 11:08:33,127] {dagbag.py:320} ERROR - Failed to import: /c/Airflow/dags/6_dataproc_airflow.py
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/c/Airflow/dags/6_dataproc_airflow.py", line 97, in <module>
    impar_task = DataprocSubmitJobOperator(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'region'
[2023-01-31 11:08:33,240] {processor.py:653} WARNING - No viable dags retrieved from /c/Airflow/dags/6_dataproc_airflow.py
[2023-01-31 11:08:33,423] {processor.py:161} INFO - Processing /c/Airflow/dags/6_dataproc_airflow.py took 0.973 seconds
